version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./laravel:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./laravel/storage/docker/log/nginx:/var/log/nginx
    ports:
      - "80:80"
    tty:  true
    restart: unless-stopped
    container_name: nginx_laravel
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    tty:  true
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ./laravel:/var/www
      - ./laravel/storage/docker/log/nginx:/var/log/nginx
    container_name: app
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge